=== Podkolzin/-by.vsulab.task3/medications.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/medications"
        xmlns:tns="http://www.example.org/medications" elementFormDefault="qualified">
    <element name="medications">
        <complexType>
            <sequence>
                <element name="medication" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="pharm" type="string"/>
                            <element name="medicationGroup">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="ANTIBIOTIC" />
                                        <enumeration value="PAINRELIEVER"/>
                                        <enumeration value="VITAMIN"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="analogs">
                                <simpleType>
                                    <list itemType="string" />
                                </simpleType>
                            </element>
                            <element name="versions">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="PILLS" />
                                    <enumeration value="CAPSULES" />
                                    <enumeration value="POWDER" />
                                    <enumeration value="DROPS" />
                                </restriction>
                            </simpleType>
                            </element>
                            <element name="certificate">
                                <complexType>
                                    <sequence>
                                        <element name="number" type="positiveInteger" />
                                        <element name="date" type="string"/>
                                        <element name="nameOrganization" type="string"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="aPackage">
                                <complexType>
                                    <sequence>
                                        <element name="typePackage" type="string"/>
                                        <element name="countMedication" type="positiveInteger"/>
                                        <element name="price" type="positiveInteger"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="dosage" type="positiveInteger"/>
                            <element name="frequencyOfUse" type="positiveInteger"/>
                        </sequence>
                        <attribute name="id" type="string" use="required" />
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Podkolzin/-by.vsulab.task3/medications.xml
<?xml version="1.0" encoding="UTF-8"?>
<medications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.org/medications" xsi:schemaLocation="http://www.example.org/medications medications.xsd">
    <medication id="">
    <name>aspirin</name>
    <pharm>Bayer</pharm>
    <medicationGroup>ANTIBIOTIC</medicationGroup>
    <analogs>Кетонал</analogs>
    <versions>PILLS</versions>
    <certificate>
        <number>1</number>
        <date>23052020</date>
        <nameOrganization>"MINSKGAS"</nameOrganization>
    </certificate>
    <aPackage>
        <typePackage>Box</typePackage>
        <countMedication>20</countMedication>
        <price>15</price>
    </aPackage>
    <dosage>20</dosage>
    <frequencyOfUse>12</frequencyOfUse>
</medication>
    <medication id="">
        <name>Viagra</name>
        <pharm>Pfizer</pharm>
        <medicationGroup>VITAMIN</medicationGroup>
        <analogs>Нет</analogs>
        <versions>PILLS</versions>
        <certificate>
            <number>2</number>
            <date>28052021</date>
            <nameOrganization>"MINSKFARM"</nameOrganization>
        </certificate>
        <aPackage>
            <typePackage>Box</typePackage>
            <countMedication>10</countMedication>
            <price>35</price>
        </aPackage>
        <dosage>15</dosage>
        <frequencyOfUse>4</frequencyOfUse>
    </medication>





</medications>
